// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVaWBrc3ciPYb5dLLM6S2fmLXvy8ELNho',
    appId: '1:722507420853:web:3613e45075ee7d30fe5afc',
    messagingSenderId: '722507420853',
    projectId: 'flutter-demo-da8fe',
    authDomain: 'flutter-demo-da8fe.firebaseapp.com',
    storageBucket: 'flutter-demo-da8fe.firebasestorage.app',
    measurementId: 'G-ZMMPVSGKTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-VZxPX_dXOisjj0oSZORXnhRWm1jtx8',
    appId: '1:722507420853:android:ecca88f3ffecd6cafe5afc',
    messagingSenderId: '722507420853',
    projectId: 'flutter-demo-da8fe',
    storageBucket: 'flutter-demo-da8fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5aD_xA3eQcq5kojM-Si6KI3iyzyp-UdI',
    appId: '1:722507420853:ios:9c81fafc4d5bbd17fe5afc',
    messagingSenderId: '722507420853',
    projectId: 'flutter-demo-da8fe',
    storageBucket: 'flutter-demo-da8fe.firebasestorage.app',
    iosBundleId: 'com.example.demoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVaWBrc3ciPYb5dLLM6S2fmLXvy8ELNho',
    appId: '1:722507420853:web:2784b19ed44bbd76fe5afc',
    messagingSenderId: '722507420853',
    projectId: 'flutter-demo-da8fe',
    authDomain: 'flutter-demo-da8fe.firebaseapp.com',
    storageBucket: 'flutter-demo-da8fe.firebasestorage.app',
    measurementId: 'G-RG92YZ3668',
  );
}
